using ChatProtoDataStruct;
using NGTSqlServer;

namespace ChatProtoDatabase
{
    public class SimpleResult { public int Result { get; set; } }

    // need to define binding result type
    public partial class ChatCreate : SqlServerStoredProcedure<ChatInfo> { }
    public partial class ChatInquiry : SqlServerStoredProcedure<ChatInfo> { }
    public partial class ChatRoomCreate : SqlServerStoredProcedure<ChatRoomInfo> { }
    public partial class ChatRoomInquiry : SqlServerStoredProcedure<ChatRoomInfo> { }
    public partial class ChatRoomJoin : SqlServerStoredProcedure<SimpleResult> { }
    public partial class ChatRoomLeave : SqlServerStoredProcedure<SimpleResult> { }
    public partial class ChatRoomListInquiry : SqlServerStoredProcedure<ChatRoomInfo> { }
    public partial class ChatRoomUserInquiry : SqlServerStoredProcedure<UserInfo> { }
    public partial class UserChatRoomListInquiry : SqlServerStoredProcedure<ChatRoomInfo> { }
    public partial class UserCreate : SqlServerStoredProcedure<UserInfo> { }
    public partial class UserDelete : SqlServerStoredProcedure<SimpleResult> { }
    public partial class UserInquiry : SqlServerStoredProcedure<UserInfo> { }


    // can be AutoGenerated codes..
    public partial class ChatCreate
    {
        public long ChatRoomId { get; set; }
        public long UserId { get; set; }
        public string ChatText { get; set; }
        public override string GetCommand() { return $"dbo.ChatCreate {ChatRoomId}, {UserId}, '{ChatText}'"; }
    }
    public partial class ChatInquiry
    {
        public long ChatRoomId { get; set; }
        public long LatestChatId { get; set; }
        public int Count { get; set; }
        public override string GetCommand() { return $"dbo.ChatInquiry {ChatRoomId}, {LatestChatId}, {Count}"; }
    }
    public partial class ChatRoomCreate
    {
        public long UserId { get; set; }
        public string Title { get; set; }
        public override string GetCommand() { return $"dbo.ChatRoomCreate {UserId}, '{Title}'"; }
    }
    public partial class ChatRoomInquiry
    {
        public long ChatRoomId { get; set; }
        public override string GetCommand() { return $"dbo.ChatRoomInquiry {ChatRoomId}"; }
    }
    public partial class ChatRoomJoin
    {
        public long ChatRoomId { get; set; }
        public long UserId { get; set; }
        public override string GetCommand() { return $"dbo.ChatRoomJoin {ChatRoomId}, {UserId}"; }
    }
    public partial class ChatRoomLeave
    {
        public long ChatRoomId { get; set; }
        public long UserId { get; set; }
        public override string GetCommand() { return $"dbo.ChatRoomLeave {ChatRoomId}, {UserId}"; }
    }
    public partial class ChatRoomUserInquiry
    {
        public long ChatRoomId { get; set; }
        public override string GetCommand() { return $"dbo.ChatRoomUserInquiry {ChatRoomId}"; }
    }
    public partial class ChatRoomListInquiry
    {
        public override string GetCommand() { return $"dbo.ChatRoomListInquiry"; }
    }
    public partial class UserChatRoomListInquiry
    {
        public long UserId { get; set; }
        public override string GetCommand() { return $"dbo.UserChatRoomListInquiry {UserId}"; }
    }
    public partial class UserCreate
    {
        public string Nickname { get; set; }
        public string Password { get; set; }
        public override string GetCommand() { return $"dbo.UserCreate '{Nickname}', '{Password}'"; }
    }
    public partial class UserDelete
    {
        public long UserId { get; set; }
        public override string GetCommand() { return $"dbo.UserDelete {UserId}"; }
    }
    public partial class UserInquiry
    {
        public string Nickname { get; set; }
        public string Password { get; set; }
        public override string GetCommand() { return $"dbo.UserInquiry '{Nickname}', '{Password}'"; }
    }
}
